### ISSUE TITLE
Rename all maps to tricksurf_[mapname] to make it simpler to load maps

### ISSUE THREAD

**Issue by ghost** [tricksurf/tricksurfmaps#1]
I would rename all the maps to tricksurf_[mapname] so that people who are loading the maps for the first time don't have to.

**Comment by tricksurf** [comment]
I won't do this. The upcoming Momentum Mod update uses the prefix tsurf_. I renamed them from tricksurf_ to tsurf_ a while ago to account for this. I don't want to go through the process of renaming them all and building cubemaps again.
